export const signupStyles = {
    pageContainer: "min-h-screen w-full flex items-center justify-center bg-neutral-950 text-neutral-100 p-4 sm:p-6 relative overflow-hidden font-sans selection:bg-neutral-800 selection:text-white py-10",
    backgroundGlow: "absolute -top-40 left-1/2 -translate-x-1/2 w-[650px] h-[350px] bg-gradient-to-b from-neutral-800/20 via-neutral-900/10 to-transparent blur-3xl pointer-events-none -z-10",
    card: "w-full max-w-lg bg-neutral-900/80 backdrop-blur-xl border border-neutral-800/80 rounded-2xl p-6 sm:p-8 shadow-2xl shadow-black/60 space-y-6 relative z-10 transition-all duration-200",
    header: "flex flex-col items-center text-center space-y-1.5",
    brandBadge: "w-11 h-11 rounded-xl bg-gradient-to-b from-neutral-800 to-neutral-900 border border-neutral-700/60 flex items-center justify-center text-white shadow-inner mb-2",
    title: "text-2xl font-semibold tracking-tight text-white",
    subtitle: "text-sm text-neutral-400",
    errorBanner: "flex items-start gap-2.5 p-3.5 text-xs sm:text-sm text-rose-300 bg-rose-950/40 border border-rose-900/60 rounded-xl leading-relaxed",
    form: "space-y-4",
    nameGrid: "grid grid-cols-1 sm:grid-cols-2 gap-3.5",
    fieldGroup: "space-y-1.5 text-left",
    label: "block text-xs font-medium uppercase tracking-wider text-neutral-400",
    inputWrapper: "relative flex items-center",
    input: "w-full px-3.5 py-2.5 bg-neutral-950/80 border border-neutral-800 rounded-xl text-neutral-100 text-sm placeholder-neutral-600 focus:outline-none focus:ring-1 focus:ring-white/40 focus:border-neutral-600 transition-all duration-150 disabled:opacity-50 disabled:cursor-not-allowed",
    inputWithIcon: "w-full pl-3.5 pr-11 py-2.5 bg-neutral-950/80 border border-neutral-800 rounded-xl text-neutral-100 text-sm placeholder-neutral-600 focus:outline-none focus:ring-1 focus:ring-white/40 focus:border-neutral-600 transition-all duration-150 disabled:opacity-50 disabled:cursor-not-allowed",
    passwordToggle: "absolute right-2.5 text-neutral-500 hover:text-neutral-200 focus:outline-none transition-colors p-1 cursor-pointer",
    submitButton: "w-full py-2.5 px-4 bg-white hover:bg-neutral-200 active:scale-[0.99] text-neutral-950 font-medium text-sm rounded-xl transition-all duration-150 flex items-center justify-center gap-2 shadow-sm disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:bg-white mt-2",
    footer: "text-center text-xs text-neutral-400 pt-2 border-t border-neutral-800/60",
    footerLink: "font-medium text-white hover:text-neutral-200 underline underline-offset-4 transition-colors ml-1",
};
